### ISSUE TITLE
Question: what's the point of Raw vs. Refined actions? 

### ISSUE THREAD

**Issue by 1oo7** [ReSwift/Recombine#7]
Question: what's the point of Raw vs. Refined actions? 

Generally in redux, every single action passes through each middleware exactly once. The job of middleware isn't typically to modify actions before they hit the reducers. Rather, middleware is typically just supposed to handle any side-effects that actions might incur—for example, logging. If an action should kick-off some asynchronous operation, which upon completion kicks off a different action, that subsequent action should still pass through all the same middleware as the first. 

So I'm having trouble to understand why there would be special, "refined" actions that are immune to the middleware—they go straight to the reducers. Why? How are we supposed to log these actions, if they never hit the middleware? 

A consequence of this design is that if you want to log every action, now you must make two actions for each action: a "raw" and a "refined" version, to force it to pass through the middleware. 

I'm not convinced that this extra complexity actually improves the design. Personally I would think it better to simply have one kind of Action, and they always pass through the middleware. But I'm curious to know why you went this route of Raw & Refined actions? What was the use-case that you ran into, which made you complicate the API like this? 

Thanks

**Comment by Qata** [comment]
I’m actually working on separating Middleware into two separate entities, and renaming the one that processes asynchronous actions to `Thunk`. It’s not up to date with my local copy but I’m putting this work on the 2.0 branch.

Having the async middleware deal with a separate kind of action is something I wanted to do in order to alleviate this feeling of messiness that Redux has. If any action can be asynchronously handled, all actions can become non-deterministic. It just didn’t sit well with me.

**Comment by Qata** [comment]
In the current design, if you wanted to log actions, you could create a raw action that takes your refined action type as an associated value, so you don’t have to create two actions for everything you want logged.
