### ISSUE TITLE
Why is there only one middleware?

### ISSUE THREAD

**Issue by 1oo7** [ReSwift/Recombine#8]
Why does BaseStore only take a single middleware? What if you want to run multiple middleware, such as logging middleware, usage analytics middleware, performance metrics middleware, etc.?

**Comment by Qata** [comment]
Good point, I can change that.

**Comment by Qata** [comment]
After looking into it and considering how this would essentially mean that your middleware isn't a switch-based system (losing the type checking) since you'd be reacting to specific cases in specific middleware, I've decided against it.

There's nothing stopping you from creating static functions and calling them from the middleware, which still allows you to have multiple independent places to store your business logic, but also ensures a well-typed implementation.

**Comment by Qata** [comment]
Here's an example:

```
extension Redux {
    static let middleware: Middleware<State, Action.Raw, Action.Refined> = Middleware { state, action -> AnyPublisher<Action.Refined, Never> in
        switch action {
        case let .networkCall(url):
            return URLSession.shared
                .dataTaskPublisher(for: url)
                .flatMap { data, _ in
                    state.map {
                        .modify(.set($0.counter + data.count))
                    }
                }
                .catch { error in
                    Just(.setText(error.localizedDescription))
                }
                .eraseToAnyPublisher()
        case .reset:
            return MiddlewareFunctions.reset()
        }
    }
    
    enum MiddlewareFunctions {
        static func reset() -> AnyPublisher<Action.Refined, Never> {
            [
                .modify(.set(0)),
                .setText(nil)
            ]
            .publisher
            .eraseToAnyPublisher()
        }
    }
}
```

**Comment by Qata** [comment]
There has been a big overhaul in the way that middleware works (such as renaming what was previously middleware to `Thunk`). Have a look, and if you still have concerns, open another issue with them.
